### ISSUE TITLE
es 7.16 以上版本 需要header 

### ISSUE THREAD

**Issue by wajika** [zpoint/idataapi-transform#10]
```
PS D:\ziliao\study resource\ELK\elasticsearch\数据迁移\idataapi-transform\idataapi_transform> python 2.py
[2022-04-24 11:09:40] base.py[line:288] WARNING POST http://es.lonsid.cn:9200/iot_prd_iotmessage*/_doc/_search?scroll=1m [status:
[2022-04-24 11:09:40] CSVWriter.py[line:93] INFO ./result.csv write done, total filtered 0 item, total write 0 item
Traceback (most recent call last):
  File "D:\ziliao\study resource\ELK\elasticsearch\数据迁移\idataapi-transform\idataapi_transform\2.py", line 38, in <module>
    loop.run_until_complete(example())
  File "C:\Users\wxx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\ziliao\study resource\ELK\elasticsearch\数据迁移\idataapi-transform\idataapi_transform\2.py", line 32, in example
    async for items in es_getter:
  File "C:\Users\wxx\AppData\Local\Programs\Python\Python39\lib\site-packages\idataapi_transform\DataProcess\DataGetter\ES
    self.result = await self.es_client.search(
  File "C:\Users\wxx\AppData\Local\Programs\Python\Python39\lib\site-packages\idataapi_transform\DataProcess\Config\ESConf
    return await self.transport.perform_request(
  File "C:\Users\wxx\AppData\Local\Programs\Python\Python39\lib\site-packages\idataapi_transform\DataProcess\Config\ESConf
    raise e
  File "C:\Users\wxx\AppData\Local\Programs\Python\Python39\lib\site-packages\idataapi_transform\DataProcess\Config\ESConf
    status, headers, data = await connection.perform_request(
    self._raise_error(response.status, raw_data)
  File "C:\Users\wxx\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch7\connection\base.py", line 328
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch7.exceptions.TransportError: TransportError(406, 'Content-Type header [application/octet-stream] is not supported', 
[2022-04-24 11:09:40] base_events.py[line:1738] ERROR Unclosed client session
```

idataapi-transform.ini 我加上header 但是调试的时候发现 es_client 并没有拿到这个值
[es]
hosts = ["es.cn:9200"]
headers = {"Content-Type": "application/json"}

**Comment by zpoint** [comment]
idataapi-transform 哪个版本

**Comment by wajika** [comment]
> idataapi-transform 哪个版本

pip install 下载的 应该是最新版

**Comment by zpoint** [comment]
> > idataapi-transform 哪个版本
> 
> pip install 下载的 应该是最新版

那是哪个版本呢? `pip list | grep idata`

**Comment by wajika** [comment]
2.0.1

**Comment by wajika** [comment]
我将 elasticsearch py 降低到7.14就可以用了，暂时关闭工单

**Comment by zpoint** [comment]
@wajika 之前 `requirement.txt` 里面直接指定的是大于某个版本的 `elasticsearch py`, 后面应该是 `elasticsearch` 升级了导致不兼容了, 我临时在 2.0.2 的 `requirement.txt` 改成指定了 `elasticsearch py` 版本

你这样降级也可以, 更好的方法是我后面有时间的时候改一下代码适配最新的 `elasticsearch py`

**Comment by wajika** [comment]
@zpoint 好的。
