### ISSUE TITLE
TypeError: 'noop' object is not iterable

### ISSUE THREAD

**Issue by wajika** [zpoint/idataapi-transform#6]
es 7.10版本，按官方文档说Elasticsearch Async Client仓库已经被遗弃，TypeError: 'noop' object is not iterable提示是版本不支持吗？

transform ES csv "apm-*-error-*:_doc" --max_limit=5
[2021-07-19 11:28:23] CSVWriter.py[line:96] INFO /home/wjk/idataapi-transform/result.csv write done, total filtered 0 item, total write 0 item
Traceback (most recent call last):
  File "/usr/local/python36/bin/transform", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/cli.py", line 195, in main
    loop.run_until_complete(getter_to_writer(getter, writer))
  File "/usr/local/python36/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/cli.py", line 133, in getter_to_writer
    async for items in getter:
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/DataProcess/DataGetter/ESGetter.py", line 33, in __anext__
    scroll=self.config.scroll, body=self.config.query_body)
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/DataProcess/Config/ESConfig.py", line 82, in main_loop
    method, url, params, body, ignore=ignore, timeout=timeout, headers=headers)
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/DataProcess/Config/ESConfig.py", line 145, in perform_request
    yield from response.release()
TypeError: 'noop' object is not iterable

**Comment by zpoint** [comment]
@wajika 可以了
pip 更新下, 安装 2.0.0 版本

由于 es 7.0+ 默认没有 doc_type, 并且 scroll api返回结构变更
使用工具时候 2.0.0 以上版本不需要传 doc_type, 只用传 index
并且2.0.0 版本只支持 es 7.0+, 不向下兼容

**Comment by wajika** [comment]
> @wajika 可以了
> pip 更新下, 安装 2.0.0 版本
> 
> 由于 es 7.0+ 默认没有 doc_type, 并且 scroll api返回结构变更
> 使用工具时候 2.0.0 以上版本不需要传 doc_type, 只用传 index
> 并且2.0.0 版本只支持 es 7.0+, 不向下兼容

ok，我试下

**Comment by wajika** [comment]
还缺什么？我已经装了elasticsearch_async 

```
transform ES csv "apm-*-error-*:_doc" --max_limit=500
Traceback (most recent call last):
  File "/usr/local/python36/bin/transform", line 7, in <module>
    from idataapi_transform import main
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/__init__.py", line 3, in <module>
    from .cli import main
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/cli.py", line 4, in <module>
    from .DataProcess.Config.DefaultValue import DefaultVal
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/DataProcess/Config/DefaultValue.py", line 3, in <module>
    from .MainConfig import main_config
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/DataProcess/Config/MainConfig.py", line 6, in <module>
    from .ESConfig import init_es
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/DataProcess/Config/ESConfig.py", line 5, in <module>
    from elasticsearch._async.transport import AsyncTransport as OriginAsyncTransport
ModuleNotFoundError: No module named 'elasticsearch._async'
```

**Comment by zpoint** [comment]
pip uninstall elasticsearch_async
pip install elasticsearch>7.8.0

**Comment by wajika** [comment]
> @wajika
> 
> ```shell
> pip uninstall elasticsearch_async
> pip install elasticsearch>7.8.0
> ```
> 
> 我的验证过的版本
> 
> ```shell
> pip list | grep elast   
> elasticsearch              7.13.3
> ```

```
[root@k8s-node1 opt]# transform ES csv "apm-*-error-*:_doc" --max_limit=500
[2021-07-20 16:07:24] CSVWriter.py[line:96] INFO /opt/result.csv write done, total filtered 0 item, total write 0 item
Traceback (most recent call last):
  File "/usr/local/python36/bin/transform", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/cli.py", line 195, in main
    loop.run_until_complete(getter_to_writer(getter, writer))
  File "/usr/local/python36/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/cli.py", line 133, in getter_to_writer
    async for items in getter:
  File "/usr/local/python36/lib/python3.6/site-packages/idataapi_transform/DataProcess/DataGetter/ESGetter.py", line 33, in __anext__
    scroll=self.config.scroll, body=self.config.query_body)
  File "/usr/local/python36/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
TypeError: search() got an unexpected keyword argument 'headers'
```

**Comment by zpoint** [comment]
@wajika 

没复现, pip elasticsearch 和 idataapi-transform 的版本发一下,  elasticsearch 源码里有 headers 参数

![image](https://user-images.githubusercontent.com/18083296/126426180-fafce30a-cade-41f5-85de-c36ebceeaef4.png)


升级到 2.0.1, 增加下面的账号和密码选项

```ini
[es]

http_auth = ["username", "password"]
```

这是我 pip list 的版本

```shell
zpoint@ZEPINGGUO-MB0 Desktop % pip list | grep elasticsearch    
elasticsearch              7.13.3
zpoint@ZEPINGGUO-MB0 Desktop % pip list | grep idata        
idataapi-transform         2.0.1
```

**Comment by wajika** [comment]
我抽空再测试一下

**Comment by zpoint** [comment]
@wajika 

应该是不用去掉 header 也能跑的🦆

程序是分批写入的, 拉数据->写数据->拉数据->写数据这样循环
表头必须写在最前面, 也是是第一次根据第一批数据(你这里是前100条)自动生成的, 你前一百条数据的表头里没有 'user', 'container' 字段
后面拉到的数据又有  'user', 'container', 导致这个报错


解决方法:

1. 用命令行
1.1 指定查询条件, 把字段完整的数据排序排在前面
1.2 或者你写一个拦截函数, 把完整字段都填充进去
具体参考 [readme](https://github.com/zpoint/idataapi-transform/blob/master/README_CN.md)
![image](https://user-images.githubusercontent.com/18083296/126586162-88717321-8700-48ce-a701-01b3251ac01b.png)

2. 用程序
WCSVConfig 支持传 headers 参数, 如果传了就根据这个生成表头, 不然就根据拉到的第一批数据生成

**Comment by zpoint** [comment]
@wajika 

或者用 xlsx, xlsx 支持动态写表头, 就不会报错
但是 xlsx 的写入速度比 csv 慢

**Comment by zpoint** [comment]
@wajika

你是不是装了几个版本的 python 呢

你命令行输入 `transfrom` 调用的 python 和 `pip list` 调用的一样么

```shell
zpoint@ZEPINGGUO-MB0 ~ % which transform 
/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/transform
zpoint@ZEPINGGUO-MB0 ~ % which pip
/Users/zpoint/Library/Python/3.9/bin/pip
zpoint@ZEPINGGUO-MB0 ~ % pip --version
pip 21.1.3 from /Users/zpoint/Library/Python/3.9/lib/python/site-packages/pip (python 3.9)
zpoint@ZEPINGGUO-MB0 ~ % 
``` 

我看你前面贴的报错是
```python3
TypeError: search() got an unexpected keyword argument 'headers'
```
但是查看 `elasticsearch       7.13.3 ` 的源码 search 方法是有定义 `headers` 参数的🦆

**Comment by wajika** [comment]
> @wajika
> 
> 应该是不用去掉 header 也能跑的🦆
> 
> 程序是分批写入的, 拉数据->写数据->拉数据->写数据这样循环
> 表头必须写在最前面, 也是是第一次根据第一批数据(你这里是前100条)自动生成的, 你前一百条数据的表头里没有 'user', 'container' 字段
> 后面拉到的数据又有 'user', 'container', 导致这个报错
> 
> 解决方法:
> 
> 1.1 或 1.2 或 2 其中一个就可以解决, 不用都尝试
> 
> 1. 用命令行
>    1.1 指定查询条件, 把字段完整的数据排序排在前面
>    1.2 或者你写一个拦截函数, 把完整字段都填充进去
>    具体参考 [readme](https://github.com/zpoint/idataapi-transform/blob/master/README_CN.md)
>    ![image](https://user-images.githubusercontent.com/18083296/126586162-88717321-8700-48ce-a701-01b3251ac01b.png)
> 2. 用程序
>    WCSVConfig 支持传 headers 参数, 如果传了就根据这个生成表头, 不然就根据拉到的第一批数据生成

明白意思了。

transform ES xlsx  "apm-*-error-*:_doc" --max_limit=500  这样就可以了，最简单。

**Comment by wajika** [comment]
> @wajika
> 
> 你是不是装了几个版本的 python 呢
> 
> 你命令行输入 `transfrom` 调用的 python 和 `pip list` 调用的一样么
> 
> ```shell
> zpoint@ZEPINGGUO-MB0 ~ % which transform 
> /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/transform
> zpoint@ZEPINGGUO-MB0 ~ % which pip
> /Users/zpoint/Library/Python/3.9/bin/pip
> zpoint@ZEPINGGUO-MB0 ~ % pip --version
> pip 21.1.3 from /Users/zpoint/Library/Python/3.9/lib/python/site-packages/pip (python 3.9)
> zpoint@ZEPINGGUO-MB0 ~ % 
> ```
> 
> 我看你前面贴的报错是
> 
> ```python
> TypeError: search() got an unexpected keyword argument 'headers'
> ```
> 
> 但是查看 `elasticsearch 7.13.3 ` 的源码 search 方法是有定义 `headers` 参数的🦆

[root@k8s-node1 ~]# which transform
/usr/local/python36/bin/transform

只有一个python 3.6.8

前面运行的时候 我找到get_es_client 的代码，屏蔽了header

**Comment by zpoint** [comment]
@wajika 

csv 不认 json, 只有字符串

看我上面回复的的截图，可以定义一个 filter, filter写代码把里面的 json 数据拿出来，赋到外面，这属于自己的业务逻辑哈

**Comment by wajika** [comment]
你的的意思是 output如果是csv就不会解析json是吧？
哪种output会解析json？

**Comment by zpoint** [comment]
@wajika 

哪种都不会吧

怎么定义解析呢, json 对象可以很多层嵌套, 你把第一层的的key, value取出来放外面? 把列表的第一个(如果还是列表)再取第一个所有 key, value 取出来放外面?
如果 value 还是列表或obect 呢, 怎么取

个人认为工具这样处理是合适的, 你不用数据json里面的结构不一样, 需求不一样, 具体你只需要写个函数按你想要的方式提出来就行呢
