### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by wajika** [zpoint/idataapi-transform#9]
windows and python3.9 
es:7.16.3
elasticsearch-py 7.14.2

`transform ES csv "iot_prd_iotmessage*" --w_encoding gbk --query_body '{"query":{"bool":{"filter":[{"range":{"@timestamp":{"from":"now-1d/d","to":"now-1d/d"}}},{"term":{"type":1}}]}},"sort":{"@timestamp":{"order":"asc"}}}'`

```
C:\Users\administrator\Desktop>transform ES csv "iot_prd_iotmessage*" --w_encoding gbk --query_body '{"query":{"bool":{"filter":[{"range":{"@timestamp":{"from":"now-1d/d","to":"now-1d/d"}}},{"term":{"type":1}}]}},"sort":{"@timestamp":{"order":"asc"}}}'
Traceback (most recent call last):
  File "C:\Users\administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\idataapi_transform\cli.py", line 165, in main
    from_kwargs["query_body"] = json.loads(args.query_body)
  File "C:\Users\administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\administrator\AppData\Local\Programs\Python\Python39\Scripts\transform.exe\__main__.py", line 7, in <module>
  File "C:\Users\administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\idataapi_transform\cli.py", line 167, in main
    raise SyntaxError("--query_body must be json serialized")
SyntaxError: --query_body must be json serialized
```

我转换过文件编码 dos2unix，然后也 重新保存文件 为UTF-8编码，再次运行都是这个错误

**Comment by zpoint** [comment]
该命令行在 mac 下执行解析正常, 无win环境测试

**Comment by wajika** [comment]
在linux下同样的命令是可以运行的，好奇怪为什么windows下就会有问题。疑难杂症 暂时关闭
